/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sopadeletrass;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import sopadeletrass.Grafos;

/**
 *
 * @author KelvinCi
 */
public class Txt extends javax.swing.JFrame {

    public Grafos grafo;
    public String[] diccionario;
    public String path;
    /**
     * Creates new form Txt
     */
    public Txt() {
        initComponents();
        this.setVisible(true);
    }

    

    public Grafos leerTXT(String direccion_txt) {


        String datos = "";
        String linea;
        String datos_txt = "";
        String path = direccion_txt;
        int modo = 1;
        File file = new File(path);
        String lineas[];
        try {
            if (!file.exists()) {
                file.createNewFile();
            } else {
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);
                while ((linea = br.readLine()) != null) {
                    if (!linea.isEmpty() && !linea.equals("dic")) {
                        if (linea.equals("tab")) {
                            modo = 2;
                        } else if (linea.equals("/dic") || linea.equals("/tab")) {
                        } else if (modo == 1) {
                            datos_txt += (linea) + ",";
                        } else if (modo == 2) {
                            linea = linea.replace(" ", "");
                            linea = linea.replace(",", "");
                            System.out.println(linea);
                            this.grafo = new Grafos(16);
                            for (int i = 0; i < linea.length(); i++) {
                                grafo.insertar_vertices(linea.charAt(i));
                            }
                            this.armarGrafo();
                            System.out.println("jdsbkjbs");
                        }
                    }
                }
                if (!"".equals(datos_txt)) {
                    datos = datos_txt;

                }
                this.diccionario = datos_txt.replace(" ", "").split(",");
                br.close();
                JOptionPane.showMessageDialog(null, "Lectura Exitosa");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        return grafo;
    }

    public void armarGrafo() {
        int[] indices = {-5, -4, -3, -1, 1, 3, 4, 5};
        for (int i = 0; i < 16; i++) {
            for (int j = 0; j < 8; j++) {
                try {
                    switch (i) {
                        case 0, 4, 8, 12 -> {
                            if (indices[j] != -5 && indices[j] != -1 && indices[j] != 3) {
                                this.grafo.insertarArista(i, i + indices[j]);
//                                this.sopa[i].agregar(this.sopa[i + indices[j]]);
                            }
                        }
                        case 3, 7, 11, 15 -> {
                            if (indices[j] != -3 && indices[j] != +1 && indices[j] != 5) {
                                this.grafo.insertarArista(i, i + indices[j]);

                            }
                        }
                        default ->
                            this.grafo.insertarArista(i, i + indices[j]);

                    }
                } catch (Exception e) {

                }
            }
        }
    }

    public String buscarArchivo() {
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de Texto", "txt");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(filter);
        File ruta = new File("e:/carpeta/");
        fileChooser.setCurrentDirectory(ruta);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String dir = String.valueOf(file).replace("\\", "//");
            return dir;
        }
        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("BuscarTxt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.path = this.buscarArchivo(); 
        this.leerTXT(this.path);
        System.out.println(this.grafo.letras[0].letra);
        ISopaDeLetras sopa = new ISopaDeLetras(this.grafo, this.diccionario, this.path);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
