/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import sopadeletrass.*;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author USUARIO
 */
public class Ventana3 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana3
     */
    public Ventana3() {
        initComponents();
    }
    
    public void crearTablero(Listaexamples listaLetras){
        NodoLista letra = listaLetras.getFirst();
        for(int i =0; i < listaLetras.getLenght(); i++) {
            
            String letraStr = String.valueOf(letra.getValor());

            Component componente = jPanel1.getComponent(i);
            if (componente instanceof JTextField) {
                JTextField textfield = (JTextField) componente;            
                textfield.setText(letraStr);
                textfield.setEditable(false);
                textfield.setHorizontalAlignment(JTextField.CENTER);
            }
            letra = letra.getDere();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        casilla1 = new javax.swing.JTextField();
        casilla2 = new javax.swing.JTextField();
        casilla3 = new javax.swing.JTextField();
        casilla4 = new javax.swing.JTextField();
        casilla5 = new javax.swing.JTextField();
        casilla6 = new javax.swing.JTextField();
        casilla7 = new javax.swing.JTextField();
        casilla8 = new javax.swing.JTextField();
        casilla9 = new javax.swing.JTextField();
        casilla10 = new javax.swing.JTextField();
        casilla11 = new javax.swing.JTextField();
        casilla12 = new javax.swing.JTextField();
        casilla13 = new javax.swing.JTextField();
        casilla14 = new javax.swing.JTextField();
        casilla15 = new javax.swing.JTextField();
        casilla16 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(237, 180, 77));
        jPanel1.setForeground(new java.awt.Color(237, 180, 77));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        casilla1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 55, 40));

        casilla2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 55, 42));

        casilla3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 55, 42));

        casilla4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 55, 42));

        casilla5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        casilla5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla5ActionPerformed(evt);
            }
        });
        jPanel1.add(casilla5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 55, 42));

        casilla6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 55, 42));

        casilla7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 55, 42));

        casilla8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 55, 42));

        casilla9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 55, 42));

        casilla10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 55, 42));

        casilla11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 55, 42));

        casilla12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 55, 42));

        casilla13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 55, 42));

        casilla14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 55, 42));

        casilla15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 55, 42));

        casilla16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(casilla16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 55, 42));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 300, 230));

        jTextArea1.setBackground(new java.awt.Color(220, 115, 34));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 150, 280));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 130, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo tablero.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casilla5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField casilla1;
    private javax.swing.JTextField casilla10;
    private javax.swing.JTextField casilla11;
    private javax.swing.JTextField casilla12;
    private javax.swing.JTextField casilla13;
    private javax.swing.JTextField casilla14;
    private javax.swing.JTextField casilla15;
    private javax.swing.JTextField casilla16;
    private javax.swing.JTextField casilla2;
    private javax.swing.JTextField casilla3;
    private javax.swing.JTextField casilla4;
    private javax.swing.JTextField casilla5;
    private javax.swing.JTextField casilla6;
    private javax.swing.JTextField casilla7;
    private javax.swing.JTextField casilla8;
    private javax.swing.JTextField casilla9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
