/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import sopadeletrass.*;

/**
 *
 * @author VivianaPetit
 */
public class Ventana5 extends javax.swing.JFrame {
    Fuentes tipoFuente;
    /**
     * Creates new form Ventana5
     */
    public Ventana5() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        tipoFuente = new Fuentes();
        jLabel1.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 24));
        jLabel6.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 17));
        jLabel3.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 16));
        jLabel2.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 16));
        jLabel4.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 16));
        jLabel5.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 16));
        jLabel7.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 16));
        jLabel8.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 16));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Interfaz.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        palabrasEncontradas = new javax.swing.JTextArea();
        panelRound2 = new Interfaz.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRound3 = new Interfaz.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelRound4 = new Interfaz.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelRound5 = new Interfaz.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        tiempo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(185, 148, 112));
        panelRound1.setRoundBottomLeft(10);
        panelRound1.setRoundBottomRight(10);
        panelRound1.setRoundTopLeft(10);
        panelRound1.setRoundTopRight(10);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        palabrasEncontradas.setEditable(false);
        palabrasEncontradas.setColumns(20);
        palabrasEncontradas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        palabrasEncontradas.setRows(5);
        jScrollPane1.setViewportView(palabrasEncontradas);

        panelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 180, 100));

        panelRound2.setBackground(new java.awt.Color(120, 61, 25));
        panelRound2.setToolTipText("");
        panelRound2.setRoundBottomLeft(10);
        panelRound2.setRoundBottomRight(10);
        panelRound2.setRoundTopLeft(10);
        panelRound2.setRoundTopRight(10);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar Palabras");
        panelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 50));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 340, 50));

        jLabel2.setForeground(new java.awt.Color(120, 61, 25));
        jLabel2.setText("Seleccione un ");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        panelRound3.setBackground(new java.awt.Color(120, 61, 25));
        panelRound3.setRoundBottomLeft(10);
        panelRound3.setRoundBottomRight(10);
        panelRound3.setRoundTopLeft(10);
        panelRound3.setRoundTopRight(10);
        panelRound3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound3MousePressed(evt);
            }
        });
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DFS");
        panelRound3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 30));

        panelRound1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 80, 30));

        jLabel4.setForeground(new java.awt.Color(120, 61, 25));
        jLabel4.setText("método de búsqueda");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        panelRound4.setBackground(new java.awt.Color(120, 61, 25));
        panelRound4.setRoundBottomLeft(10);
        panelRound4.setRoundBottomRight(10);
        panelRound4.setRoundTopLeft(10);
        panelRound4.setRoundTopRight(10);
        panelRound4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound4MousePressed(evt);
            }
        });
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BFS");
        panelRound4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 30));

        panelRound1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 80, 30));

        jLabel6.setForeground(new java.awt.Color(120, 61, 25));
        jLabel6.setText("Tiempo");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel7.setForeground(new java.awt.Color(120, 61, 25));
        jLabel7.setText("Palabras encontradas");
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        panelRound5.setBackground(new java.awt.Color(120, 61, 25));
        panelRound5.setRoundBottomLeft(10);
        panelRound5.setRoundBottomRight(10);
        panelRound5.setRoundTopLeft(10);
        panelRound5.setRoundTopRight(10);
        panelRound5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound5MousePressed(evt);
            }
        });
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Menú");
        panelRound5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));

        panelRound1.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 90, 30));

        tiempo.setEditable(false);
        tiempo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoActionPerformed(evt);
            }
        });
        panelRound1.add(tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 180, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound3MousePressed
        long startTime = System.nanoTime();
        palabrasEncontradas.setText("");
        for (int i = 0; i < Ventana2.diccionario.length; i++) {
            NodoGrafo[] l = Ventana2.grafo.dfs(Ventana2.diccionario[i]);
            String palabra = "";
            for (int j = 0; j < l.length; j++) {
                try {
                    palabra += l[j].letra;
                } catch (Exception e) {

                }
            }
            if (palabra.equals(Ventana2.diccionario[i])) {
                palabrasEncontradas.setText(palabrasEncontradas.getText() + Ventana2.diccionario[i] + "\n");
            }
        }
        long endTime = System.nanoTime();

        long timeTaken = endTime - startTime;
        tiempo.setText(String.valueOf(timeTaken / 1_000_000) + " milisegundos");
    }//GEN-LAST:event_panelRound3MousePressed

    private void panelRound4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound4MousePressed
        // TODO add your handling code here:
        palabrasEncontradas.setText("");
        long startTime = System.nanoTime();
        for (int i = 0; i < Ventana2.diccionario.length; i++) {
            AuxiliarBFS aux = Ventana2.grafo.bfsSearch(Ventana2.diccionario[i].toUpperCase());
            if (aux.encontrado) {
                palabrasEncontradas.setText(palabrasEncontradas.getText() + Ventana2.diccionario[i] + "\n");

            }
        }
        long endTime = System.nanoTime();
        long timeTaken = endTime - startTime;
        tiempo.setText(String.valueOf(timeTaken / 1_000_000) + " milisegundos");
    }//GEN-LAST:event_panelRound4MousePressed

    private void panelRound5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound5MousePressed
        Ventana3 v3 = new Ventana3();
        this.setVisible(false);
        v3.setVisible(true);
    }//GEN-LAST:event_panelRound5MousePressed

    private void tiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea palabrasEncontradas;
    private Interfaz.PanelRound panelRound1;
    private Interfaz.PanelRound panelRound2;
    private Interfaz.PanelRound panelRound3;
    private Interfaz.PanelRound panelRound4;
    private Interfaz.PanelRound panelRound5;
    private javax.swing.JTextField tiempo;
    // End of variables declaration//GEN-END:variables
}
