/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.SingleGraph;
import sopadeletrass.*;


/**
 *
 * @author VivianaPetit
 */
public class Ventana7 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana5
     */
    Fuentes tipoFuente;
    
    public Ventana7() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        tipoFuente = new Fuentes();
        jLabel3.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 16));
        jLabel1.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 24));
        jLabel2.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 20));
        jLabel4.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 20));
        jLabel5.setFont(tipoFuente.fuente(tipoFuente.nombre, 1, 16));
        
    }

    /**
     * Muestra el &aacute;rbol del recorrido BFS.
     * 
     * @param recorrido el recorrido de la busqueda
     */
    public void GraficarArbol(NodoGrafo[] recorrido) {

        Graph graph = new SingleGraph("Arbol");

        graph.setAttribute("ui.stylesheet", "node { fill-color: white; stroke-mode: plain; stroke-color: black; stroke-width: 2px; size: 30px; text-alignment: at-right; text-padding: 10px; }");

        NodoGrafo padre = null;
        for (NodoGrafo nodo : recorrido) {
            try {
                Node node = graph.addNode(nodo.pos + "");
                node.setAttribute("ui.label", nodo.letra + "");
                node.setAttribute("ui.class", "nodo");

                if (padre != null) {
                    graph.addEdge(padre.pos + "-" + nodo.pos, padre.pos + "", nodo.pos + "");
                }
                padre = nodo;
            } catch (Exception e) {

            }
        }
        System.setProperty("org.graphstream.ui", "swing");
        graph.display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Interfaz.PanelRound();
        panelRound2 = new Interfaz.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        palabra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panelRound5 = new Interfaz.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        panelRound3 = new Interfaz.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(185, 148, 112));
        panelRound1.setRoundBottomLeft(10);
        panelRound1.setRoundBottomRight(10);
        panelRound1.setRoundTopLeft(10);
        panelRound1.setRoundTopRight(10);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(120, 61, 25));
        panelRound2.setToolTipText("");
        panelRound2.setRoundBottomLeft(10);
        panelRound2.setRoundBottomRight(10);
        panelRound2.setRoundTopLeft(10);
        panelRound2.setRoundTopRight(10);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar palabra específica");
        panelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 80));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 340, 80));

        palabra.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        palabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabraActionPerformed(evt);
            }
        });
        panelRound1.add(palabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 160, 40));

        jLabel2.setForeground(new java.awt.Color(120, 61, 25));
        jLabel2.setText("Ingrese la palabra ");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        panelRound5.setBackground(new java.awt.Color(120, 61, 25));
        panelRound5.setRoundBottomLeft(10);
        panelRound5.setRoundBottomRight(10);
        panelRound5.setRoundTopLeft(10);
        panelRound5.setRoundTopRight(10);
        panelRound5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound5MousePressed(evt);
            }
        });
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menú");
        panelRound5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        panelRound1.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, 30));

        panelRound3.setBackground(new java.awt.Color(120, 61, 25));
        panelRound3.setRoundBottomLeft(10);
        panelRound3.setRoundBottomRight(10);
        panelRound3.setRoundTopLeft(10);
        panelRound3.setRoundTopRight(10);
        panelRound3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound3MousePressed(evt);
            }
        });
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buscar");
        panelRound3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 30));

        panelRound1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 100, 30));

        jLabel4.setForeground(new java.awt.Color(120, 61, 25));
        jLabel4.setText("a buscar");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void palabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palabraActionPerformed

    private void panelRound5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound5MousePressed
        Ventana3 v3 = new Ventana3();
        this.setVisible(false);
        v3.setVisible(true);
    }//GEN-LAST:event_panelRound5MousePressed

    private void panelRound3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound3MousePressed
       String palabraNueva = palabra.getText().toUpperCase();
            String regex = "[A-Za-z]+";
            Pattern pattern = Pattern.compile(regex);
            
            // Evalua que la palabra solo contenga letras y al menos 3.
            if (pattern.matcher(palabraNueva).matches() && palabraNueva.length() >= 3){
                AuxiliarBFS aux = Ventana2.grafo.bfsSearch(this.palabra.getText().toUpperCase());
                GraficarArbol(aux.recorrido);
                if (aux.encontrado) {
                    JOptionPane.showMessageDialog(rootPane, "Palabra encontrada.");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Palabra no encontrada.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error: palabra no válida.");
            }
    }//GEN-LAST:event_panelRound3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField palabra;
    private Interfaz.PanelRound panelRound1;
    private Interfaz.PanelRound panelRound2;
    private Interfaz.PanelRound panelRound3;
    private Interfaz.PanelRound panelRound5;
    // End of variables declaration//GEN-END:variables
}
