/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sopadeletrass.Listaexamples;
import java.awt.*;
import javax.swing.*;


/**
 *
 * @author KelvinCi
 */
public class Ventana2 extends javax.swing.JFrame {

    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    Listaexamples listaWord;
    Listaexamples listaLetras;

    /**
     * Creates new form ISopaDeLetras
     */
    public Ventana2() {
        initComponents();
        listaWord = new Listaexamples();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    public String AbrirArchivo(File archivo) {
        String documento = "";
        try {
            entrada = new FileInputStream(archivo);
            int ascci;
            while ((ascci = entrada.read()) != -1) {
                char caract = (char) ascci;
                documento += caract;
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Error de: " + e);

        }
        return documento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        empezarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        VolverBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empezarBtn.setBackground(new java.awt.Color(220, 115, 34));
        empezarBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        empezarBtn.setForeground(new java.awt.Color(255, 255, 255));
        empezarBtn.setText("Buscar arhivo");
        empezarBtn.setBorder(null);
        empezarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(empezarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 190, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 440, 230));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Solo archivos tipo .txtx");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Carga tu archivo con el diccionario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("y las letras para el tablero");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 20));

        VolverBtn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        VolverBtn.setForeground(new java.awt.Color(220, 115, 34));
        VolverBtn.setText("Volver");
        getContentPane().add(VolverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/background 2.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empezarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarBtnActionPerformed
        // TODO add your handling code here:
        //String letras = "C,H,A,O,X,A,T,M,P,R,R,A,A,O,R,O";

        if (seleccionar.showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionar.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("txt")) {
                    String documento = AbrirArchivo(archivo);
                    int inicioWord=documento.indexOf("dic")+"/dic".length();
                    int finWord=documento.indexOf("/dic");
                    String ParaRecorrer=documento.substring(inicioWord,finWord);
                    ParaRecorrer=ParaRecorrer.replaceAll("/n", "");
                    for (int i = 0; i < ParaRecorrer.length(); i++) {
                        char letraWords=ParaRecorrer.charAt(i);
                        listaWord.insertFinal(letraWords);
                    }
                    int inicio = documento.indexOf("tab") + "tab".length();
                    int fin = documento.indexOf("/tab");
                    String textolista = documento.substring(inicio, fin);
                    textolista = textolista.trim().replaceAll(",","");
                    
                    
                    for (int i = 0; i < textolista.length(); i++) {
                        char letra = textolista.charAt(i);
                        
                        listaLetras.insertFinal(letra);
                    }
                    
                    Ventana3.crearTablero(listaLetras);

                } else {
                    JOptionPane.showConfirmDialog(null, "Archivo no compatible");
                }
            }
        }   
    }//GEN-LAST:event_empezarBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VolverBtn;
    private javax.swing.JLabel background;
    private javax.swing.JButton empezarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
